services:
  server:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    container_name: server-container
    ports:
      - "1804:1804"
    healthcheck:
      test: [ "CMD", "pgrep", "java" ]
      interval: 10s
      retries: 3
    tty: true

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "ticketManagerDB"
      POSTGRES_USER: "postgres_admin"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      -   ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
